language: cpp

sudo: false

os:
  - linux
  - osx
  
compiler:
  - clang
  - gcc

before_install:
  - git submodule update --init --recursive

before_script:
  - echo "CC=$CXX" > make/local

matrix:
  - fast_finish: true

script:
  - git submodule foreach 'echo $path `git rev-parse HEAD`'
  - ./runCmdStanTests.py src/test/interface
