language: cpp

sudo: false

os:
  - linux
  - osx
  
compiler:
  - clang
  - gcc

before_install: make math-revert

before_script: echo "CC=$CXX" > make/local

matrix:
  fast_finish: true

env:
  -  TESTFOLDER=src/test/unit/interface_callbacks
  -  TESTFOLDER=src/test/unit/io
  -  TESTFOLDER=src/test/unit/lang
  -  TESTFOLDER=src/test/unit/mcmc
  -  TESTFOLDER=src/test/unit/model
  -  TESTFOLDER=src/test/unit/optimization
  -  TESTFOLDER=src/test/unit/services
  -  TESTFOLDER=src/test/unit/variational

script: ./runTests.py $TESTFOLDER
